### ISSUE TITLE
handlel multiple movies for /add movie 

### ISSUE THREAD

**Issue by nrossetti** [nrossetti/movie-time#10]
be able to pass list 
commas, spaces, or tabs.

**Comment by charliemarshall1996** [comment]
Hi, I'm happy to have a go at this. By list, I guess you mean more than just a list object, but also delimited collections of data that can be imported from a .csv or .txt file?

Also, to confirm, this is for the def add_movie function in the db_manager.py file?

**Comment by eruditmorina** [comment]
@nrossetti I worked on implementing this feature. Can I please have permission to open a PR about it?

**Comment by nrossetti** [comment]
Hi @eruditmorina,
Thanks for taking the initiative. Feel free to open a PR for review.
If you are looking to contribute, I'll flesh out my issue details more and update my README, as I was currently using them more so for my own tracking.
Thanks

**Comment by eruditmorina** [comment]
@nrossetti I am trying to create a new branch to push my changes, but it seems I do not have the correct access rights. Is it something you can help with? I would be grateful.

**Comment by eruditmorina** [comment]
Hey @nrossetti sorry for the inconvenience, here is the link to the PR:
https://github.com/nrossetti/movie-time/pull/12

**Comment by nrossetti** [comment]
Hey @eruditmorina,
No inconvenience at all, and thanks for opening the PR! I'm new to managing and contributing to open-source public repos myself, so we're both learning here. I've seen the PR and will review it as soon as I can.

I'll be working on configuring the repo's branches and documentation this evening to better align with the open-source model.

cheers!

**Comment by nrossetti** [comment]
Looks great, thanks @eruditmorina
