### ISSUE TITLE
allow editing of movie nights

### ISSUE THREAD

**Issue by nrossetti** [nrossetti/movie-time#6]
allow editing of titles and descriptions for a movie night

This should be a separate slash command **/edit_movie_night**

- 3 optional arguments, the movie night id,  name, and description
- if the id is not passed, get the latest movie id (same as with the `/add movies` command) 
- for the name and description, update them if they are passed in the command

**Comment by Sanyam-jain30** [comment]
I can work on it. Please assigne it to me.

**Comment by nrossetti** [comment]
@Sanyam-jain30 feel free to give it a shot. i updated the details for the issue
